name: main_workflow
on: [push]
run-name: running tests for ${{github.actor}}
jobs:
  automatic_testing:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "we are building ci" > generated.txt
      - run: ls -la
      - run: cat generated.txt
